name: Entry Deployment Pipeline
on: 
  push:
    branches:
    - fixes
  release:
    types:
    - created

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Yarn
        run: yarn install
      
      - name: Publish Extension
        run: npm run deploy --verbose
        env:
          VSCE_PAT: h53oxpq3k2fmfc2zgv3wocrhoh634w46qtg4vdymikthllkjtola