name: Entry Deployment Pipeline
on: 
  push:
    branches:
      - fixes

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Install vsce
        run: npm install -g vsce
      
      - name: Login to Azure Devops
        env:
          VSCODE_TOKEN: 'zyq6epeclsnru437xqoeviopfqhnbjf4wxneqd4fwbnmi5t7vvta'
        run: vsce login Entry
      
      - name: Publish Extension
        run: vsce publish