name: Entry Unit Test Pipeline
on: 
  push:
      branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        env:
          DISPLAY: ":99"




